String getjsonData = '''
{
  "states": [
    {
      "name": "Meghalaya",
      "districts": [
        "North Garo Hills",
        "Ri Bhoi"
      ],
      "department": [
        "Department of Business Development"
      ],
      "districts_Village": [
        {
          "name": "North Garo Hills",
          "city": [
            "Dagal Songgitcham",
            "Lower Manikganj",
            "Genang",
            "Moranodi",
            "Dagal Songgitcham",
            "Thapa Dangre"
          ]
        },
        {
          "name": "Ri Bhoi",
          "city": [
            "Plasha Ribhoi District",
            "Umkon Nongtluh",
            "Mawlong Nongtluh",
            "Diwon Nongtluh",
            "Jermanai Nongtluh Ribhoi",
            "Mawker Nongkhap ribhoi",
            "Umdohkha Nongtluh",
            "Umterlen Nongtluh",
            "Sohkhar",
            "Umpyrdong",
            "Kynton Phanram",
            "Umden Khasi BPO Umden PO Nongpoh",
            "Ri-Bhoi",
            "Korstep Nonglyngdoh",
            "NONGPOH",
            "Umdohkha Them",
            "DIWON RAID NONGTLUH",
            "SHILLONG",
            "Umdeng Diwon"
          ]
        }
      ]
    },
    {
      "name": "Arunachal Pradesh",
      "districts": [
        "Anjaw",
        "East Kameng",
        "East Siang",
        "Lohit",
        "Papum Pare",
        "Tirap",
        "West Kameng"
      ],
      "department": [
        "Department of Business Development",
        "Department of Livelihood and Entrepreneurship"
      ],
      "districts_Village": [
        {
          "name": "Anjaw",
          "city": [
            "Hayuliang",
            "Tafraliang"
          ]
        },
        {
          "name": "East Kameng",
          "city": [
            "Pakke Town",
            "Pakke",
            "Taoso"
          ]
        },
        {
          "name": "East Siang",
          "city": [
            "Oyan"
          ]
        },
        {
          "name": "Lohit",
          "city": [
            "Khoraliang",
            "Khoraba vill",
            "Duraliang",
            "Vill- jeinko",
            "Mekailiang",
            "Tafragam",
            "Tezu",
            "Chailiang",
            "Thowang",
            "Tezu lohit",
            "19th mile",
            "Yealiang",
            "Hayuliang",
            "Tafraliang",
            "Danglat",
            "Village duraliang p.o/p.s tezu",
            "Village changliang p.o/p.s tezu",
            "Tezu, p.o/p.s tezu",
            "Village tamblu p.o/p.s hayuliang",
            "19mile"
          ]
        },
        {
          "name": "Papum Pare",
          "city": [
            "Tayeng Tarang",
            "DOBAM VILLAGE",
            "Itanagar",
            "Doimukh papum pare",
            "Naharlagun",
            "Chimpu",
            "bandardawa dobam papum pare",
            "Banderdewa upper dobam papum pare",
            "Dobam bandardawa papum pare",
            "Kimin shantinagar papum pare",
            "Kimin",
            "Durpa Village kimin papum pare",
            "Kimin takar vilage papum pare",
            "Kimin khuda vilage papum pare",
            "East kameng pakke kessang",
            "east kameng pakke kessang",
            "Nirjuli papum pare",
            "Chessa sonajuli papum pare",
            "Chessa",
            "chessa papum pare a.p",
            "Kimin deep papum pare",
            "Yupia nyorch papum pare",
            "Yupia",
            "Upper nyorch papum pare yupia",
            "Lower emchi papum pare",
            "Doimukh",
            "Lower emchi papum pare",
            "Banderdewa",
            "Banderdewa upper dobam",
            "Upper dobam"
          ]
        },
        {
          "name": "Tirap",
          "city": [
            "THINSA VILLAGE",
            "CHINKOY VILLAGE",
            "DADAM VILLAGE",
            "KHONSA TOWN",
            "CHASA VILLAGE",
            "MOKTOT VILLAGE",
            "LONGO VILLAGE",
            "LAHO VILLAGE",
            "KHELA VILLAGE",
            "DEAMOLI TOWN",
            "WASATHONG VILLAGE",
            "KHETI VILLAGE",
            "KHONSA",
            "KHELA VILLAGE"
          ]
        },
        {
          "name": "West Kameng",
          "city": [
            "Rupa",
            "Dirang",
            "Chug",
            "Nafra",
            "Munna camp,",
            "Singchung",
            "Thrizino",
            "Sinchung ",
            "Bomdila"
          ]
        }
      ]
    },
    {
      "name": "Assam",
      "districts": [
        "Baksa",
        "Barpeta",
        "Biswanath",
        "Bongaigaon",
        "Chirang",
        "Darrang",
        "Dhemaji",
        "Dhubri",
        "Dibrugarh",
        "Jorhat",
        "Kamrup",
        "Kamrup Metropolitan",
        "Karbi Anglong",
        "Kokrajhar",
        "Lakhimpur",
        "Nalbari",
        "Sivasagar",
        "Tamulpura",
        "Tinsukia",
        "Udalguri"
      ],
      "department": [
        "Department of Business Development",
        "Department of Livelihood and Entrepreneurship"
      ],
      "districts_Village": [
        {
          "name": "Baksa",
          "city": [
            "1 no Batachara",
            "2 No Bhogpara",
            "2 no kataligaon",
            "2 no Katligaon",
            "2 no Piplani",
            "Adalbari",
            "Agchia",
            "Ahopa",
            "Amamrabati",
            "Amarabati",
            "Ambari",
            "Amingaon",
            "Amlaguri",
            "Amlaguri 2",
            "Angardhowa",
            "Aohata",
            "Athiabari",
            "Badulipara",
            "Badulipara ",
            "Batachara",
            "Baganpara",
            "Bagariguri",
            "Bagulamari",
            "Bagulimari",
            "Bahbari",
            "Baksa",
            "Balaghat",
            "Balarampur",
            "Baltipar",
            "Bamunkhata",
            "Bangalipara",
            "Bangnabari",
            "Banurkhuti",
            "Bara",
            "Baraliyapar",
            "Barama",
            "Baramchari",
            "Baramsary",
            "Barbelbari",
            "Barbelbari ",
            "Zarkhona",
            "Baregaon",
            "Barigaon ",
            "Hangalpara",
            "Barkapala",
            "Barkhopa",
            "Barkuchijar",
            "Barokodali",
            "Barphena Pathar",
            "Barphena Pathar ",
            "Aamrattary",
            "Bata Garaljara",
            "Batabari R/F",
            "Batabari RF",
            "Bathouguri",
            "pakriguri",
            "Batiyamari",
            "Begarkhata",
            "Bennabari",
            "Betna",
            "Bhakatpara",
            "Bhakuatepa",
            "Bhalukdanga",
            "Bharalipara",
            "Bhogpara",
            "Bhogpur",
            "Bholabatabari",
            "Bhulukamuri",
            "Bishnupur",
            "Boko",
            "Borgaon",
            "Bunbari",
            "Chaibari",
            "Charaljani",
            "Charangbari ",
            "Tamulpur",
            "Chemethiapara",
            "Cheuni",
            "Chilakhana",
            "Chokamari",
            "Dahkhaunia",
            "Dakhin Hatsimla ",
            "Samudragar",
            "Dakhin supa",
            "Dakhinchupa",
            "Dakhinkuchi",
            "Dalangdia",
            "Dalbari",
            "Dalgaon",
            "Darrang",
            "Dhanbil",
            "Dhansripur",
            "Dhekiajuli",
            "Dhekiyajuli",
            "Dhira R/F",
            "Dighaldonga",
            "Digholdonga",
            "Dimilapar",
            "Dolajani",
            "Dolajani (Hatkhola)",
            "Dolbari",
            "Dongpar",
            "Dongpara",
            "Dwimuguri",
            "Falakata",
            "Garamdeu",
            "Garbhitor",
            "Dhamdhama",
            "Garumara",
            "Gerua",
            "Ghil",
            "Ghilajar",
            "Ghogapar",
            "Ghograkuthi",
            "Goldingpara",
            "Karemura",
            "Ulubari",
            "Gopinathpur",
            "Gopinathpur Nunar par",
            "Gopinathpur Nunarmat",
            "Goreswar",
            "Hangalpara",
            "Hangmapur",
            "Hatirtari",
            "Hatkhola",
            "Hatsimla",
            "Hazira",
            "Hirimbapur",
            "Hudukhata",
            "Hudukhata Gaon",
            "Jaigir Chilakhana",
            "Jalah ( Ghora mara)",
            "Jalahati",
            "Jamphaiguri",
            "Dhekiajuli",
            "Jargaon",
            "Jaygir chilakhana",
            "Jhingapuni",
            "Jhokmari",
            "Jhopa",
            "Jogdola",
            "Jopadong",
            "Kachubari",
            "Kachukata",
            "Kadamrala",
            "Kakakuchi",
            "Kalakuchi",
            "Kalbari",
            "Kalcheni",
            "Kaljar",
            "Kaljhar",
            "Karemura",
            "Kathalbari",
            "Kharadhara",
            "Kharua",
            "Kharuajan",
            "Khatarbari",
            "khatorbari",
            "Khwdwmguri",
            "Kumarikata",
            "Kumarpara",
            "Lakhipara",
            "Latibari",
            "Laukhata",
            "Maharipara",
            "Mainapur ",
            "Rupahi",
            "Majarabari",
            "Manikpur",
            "Maynaguri",
            "Mazdia",
            "Motipur",
            "Murmela",
            "N K Daranga",
            "Nagrijuli",
            "Namcharia",
            "Namchariya",
            "Narayanpur",
            "Natafala",
            "Natun Shripur",
            "No 1 Jaldhangpara",
            "No 1 Katligaon",
            "No 2 Axiguri",
            "No 2 Bagrikhuti",
            "No 2 Bhogpara",
            "No 2 Goreswar",
            "No 2 Pakhriguri",
            "No 3 Hirimbapur",
            "No 4 Thaijwobari",
            "Notafela",
            "Notafela",
            "Dinhata",
            "Ouguri",
            "Pachim Rihabari",
            "Pachimathiabari",
            "Pakriguri",
            "Palashguri",
            "Pamuapathar",
            "Panbari",
            "Pariguri",
            "Paschim Athiyabari",
            "Pokalagi",
            "Polokata",
            "Pub Bangnabari",
            "Pub Kasubari",
            "Pub Khagrabari",
            "Puranshripur",
            "Ramcha",
            "Rampur",
            "Ramsagar",
            "Rangapani",
            "Dwarkuchi",
            "Ruierkuthi",
            "Rupa phuli",
            "Rupahi",
            "Salbari",
            "Samudragar",
            "Samudragar",
            "hat simala",
            "Sarphutchaki",
            "Sarufulchaki",
            "Sarugati",
            "Saudarvitha",
            "Serfanguri",
            "Shalmara",
            "Notaphela",
            "Shilbari",
            "Shripur",
            "Silkajar",
            "Silkijar",
            "Simlabari",
            "Sona fuli",
            "Sona Phuli",
            "Sonafuli",
            "Suagpur",
            "Sualkuchi",
            "Sutiapara",
            "Taltal",
            "Tamulpur",
            "Teteliguri",
            "Tulsibari",
            "ULUBARI",
            "Uttar Barsiral",
            "Uttar Cheuni",
            "Uttargandhibari"
          ]
        },
        {
          "name": "Barpeta",
          "city": [
            "Akaya",
            "Banbaria",
            "Bar Kapla",
            "Barbakhora",
            "Barkapala",
            "Belbari",
            "Bengapara",
            "Besimari",
            "Bhakuatepa",
            "Bhethua",
            "Bunmajapam",
            "Byaskuchi ",
            "Chaudanga",
            "Damrabowa",
            "Dubi",
            "Gahia",
            "Gandhinagar",
            "Garatari",
            "Goraimari",
            "Haladhi Bari",
            "Katala Gaon",
            "Katla Gaon",
            "Maripur",
            "Nagaon",
            "Namati",
            "Pathshala  Ward No 4",
            "Pathshala Ward no 5",
            "Puthimari",
            "Rahmoria Niz Kanai Gaon",
            "Sagachari",
            "Sagalchari",
            "Satra Barala",
            "Shingara",
            "Shingra",
            "Titkataje"
          ]
        },
        {
          "name": "Bongaigaon",
          "city": [
            "Khagarpur"
          ]
        },
        {
          "name": "Chirang",
          "city": [
            "Amaraguri",
            "Amguri no2",
            "Ashrabari",
            "Bajugaon No1",
            "Ballamguri",
            "Banduguri",
            "Bangaldoba",
            "Bar Kapla",
            "Bar Laugaon",
            "Barbakhora",
            "Barkhata pt 2",
            "Belbari",
            "Bhadulipara",
            "Borgaon",
            "Boripara No1",
            "Borlawgaon",
            "Bowpara",
            "Byaskuchi",
            "Dangtalgaon",
            "Dhauliguri",
            "Fagunagaon",
            "Fulkumari",
            "Galapara",
            "Gerukabari",
            "Girjangaon",
            "Gossaigaon",
            "Goybari",
            "Gujwnpuri",
            "Guwabari",
            "Gurubasa",
            "Hashrawbari",
            "Jarmonbari",
            "Kachdoha",
            "Kachubil",
            "Kanthalguri",
            "Khagrabari",
            "Khaleppara",
            "Khujurabguri",
            "Kolobari",
            "Majabari",
            "Maojipara",
            "Milonpur",
            "Mistanguri",
            "Momrambari",
            "Mongolian Bazar",
            "Morabari",
            "Namalpur",
            "Namjaipara",
            "No 1 Dahlapara",
            "No 2 Pakhriguri",
            "No 2 Polashguri",
            "No 3 Chourang",
            "Panbari",
            "Pakhiguri",
            "Pachim Makra",
            "Pathargaon",
            "Pretgaon",
            "Pub Golajhar",
            "Pub Katla Gaon",
            "Rainighuli",
            "Ranchaidham",
            "Rowmari",
            "Santipur",
            "Shyamthaibari",
            "Silbari",
            "Simlaguri",
            "Soulmari",
            "South Kajalgaon",
            "Supariguri",
            "Taktara",
            "Tilapara",
            "Ulu Chapori",
            "Uttar patgaon"
          ]
        },
        {
          "name": "Darrang",
          "city": [
            "2 no majgaon",
            "BAR NAGAON",
            "BARKUMARPARA",
            "Bezpara",
            "Bidyanagar",
            "Bhairabnagar",
            "Borthekerabari",
            "CHENGELIAPARA",
            "CHOTO NAGAON",
            "Daria para",
            "Dariapara",
            "Debananda",
            "Grand land bagicha",
            "GHATUWAPARA",
            "Gerimari",
            "HAZARIKAPARA",
            "Jhakuwapara",
            "MANITARI",
            "Menapara",
            "MONITARI",
            "Nij Rangamati",
            "NIZ RANGAMATI",
            "Pachim chuburi , darrang",
            "SWETAMADAR",
            "Sipajhar",
            "Upahupara",
            "Vidyanagar",
            "barthekerabari",
            "borthekerabari",
            "dariapara",
            "barthekerabari",
            "bezapra",
            "ghatupara",
            "jhakuapara",
            "manitari",
            "monitari",
            "swetamader"
          ]
        },
        {
          "name": "Dhemaji",
          "city": [
            "2no Khalihamari",
            "Amlakhi pait, po- pipal Guri",
            "Begenagara Naharani, po- Benenagar",
            "Borpak jiamoria, po- Machkhowa",
            "Chowkham, po- Machkwa",
            "Chowkham Jatin, po- Machkwa",
            "Chowkham No1Pahukhowa, po- Machkwa",
            "Gohain Beelatia, po Machkhowa",
            "Kecherguri no - pohukhwa, po- Machkhowa",
            "Khalihamari, po- Na pomuwa",
            "Khalihamari, po- No pomuwa",
            "Khalihamari No2, po- Na pomuwa",
            "Moridhal borphukan, Po- Moridhal",
            "No 2 pahukhowa, po- Machkhowa",
            "Silikhaguri, Po-Ramya pur",
            "Amlakhi pait, po-pipal Guri",
            "Begenagara Naharani",
            "Borajan, po- Machkhowa",
            "Borbam Gohain 2 pahukhowa, po- Machkhowa",
            "Gohain Beelatia B, Po- Machkhowa",
            "Kecherguri, po- Machkhwa",
            "Mithun pathat, po- maduri pathat",
            "No 2 Borajan",
            "No2 pahukhowa, po- Machkhowa",
            "santipur konwar gaon, po- Ramaya pur",
            "Ulubani Chapori",
            "Mathikula, po, mathikula",
            "Kecherguri no pohukhwa po-Machkhowa",
            "Borbam Gohain gaon no 2 pahukhowa, po- Machkhowa",
            "DhenukhanaGaon, po- Dhenukhana"
          ]
        },
        {
          "name": "Dhubri",
          "city": [
            "Medhipara"
          ]
        },
        {
          "name": "Dibrugarh",
          "city": [
            "Tingkhong",
            "Duliajan",
            "Assam",
            "Dibrugarh",
            "Moran",
            "Khowang",
            "Jonari",
            "Dhemesi",
            "Naharkatia",
            "Sibsagar",
            "Chabua",
            "Lahowal",
            "Jorhat",
            "Namrup",
            "Lepetkata"
          ]
        },
        {
          "name": "Jorhat",
          "city": [
            "Handique gaon",
            "Abhopuria gaon",
            "Chinatali",
            "Kalipani changmai gaon",
            "Sonari gaon",
            "Burakuri gaon",
            "Hemalai moran gaon",
            "Hula gaon",
            "Lonpuria gaon",
            "Chetia gaon",
            "Podumoni gaon",
            "Panitiola rubi gaon",
            "Panitiola tinger gaon",
            "Bhagamukh charingia"
          ]
        },
        {
          "name": "Kamrup",
          "city": [
            "Darigaon",
            "Hahim",
            "Morigaon",
            "Murara Laxmi mandir",
            "No. 1. Jaysagar",
            "Pairanga",
            "River police station",
            "SeniKuthi Hill Side(ghy)",
            "Sualkuchi"
          ]
        },
        {
          "name": "Kamrup Metropolitan",
          "city": [
            "amgaon",
            "Guwahati",
            "SeniKuthi Hill Side(ghy)",
            "Kahikuchi",
            "kahikuchi Azara"
          ]
        },
        {
          "name": "Karbi Anglong",
          "city": [
            "Baliram Terang Village,Diphu",
            "Birla, Diphu",
            "Chanmari,Diphu",
            "Chephongchingri Mentila,Diphu",
            "Dok terang Village,Diphu",
            "electricity Board,Diphu",
            "Hidim teron Village,Manaj",
            "Hidisajir,Diphu",
            "Inglongcherop Village,Diphu",
            "Lindok Rongpi Village,Diphu",
            "Lumding Road, diphu",
            "Lumding Road,5 kilo, Diphu",
            "Manja",
            "Near Medical Collage, Diphu",
            "Rong Nihang-A,Diphu",
            "Rongchedon Near ITI,Diphu",
            "Rongcheto Village,Diphu",
            "Rongchingbar Village,Diphu",
            "Rongjangphong,Diphu",
            "Rongkangjang,diphu",
            "Rongkangthir Teron Village",
            "Rongklarbong,Diphu",
            "Rongmalong Village,Diphu",
            "Rongmili,Diphu",
            "Rongmirjeng village,Diphu",
            "Rongmonjir ward no.-7",
            "Rongmonjir,Diphu",
            "Sangkur Anglong, Diphu",
            "Ser Anglong Village",
            "Serlongjon,Diphu",
            "Taralangso,Diphu"
          ]
        },
        {
          "name": "Kokrajhar",
          "city": [
            "Alupara",
            "Amguri",
            "Ansaripara",
            "Ashrabari",
            "Baganpara",
            "Bagansali",
            "Bairali",
            "Bajugaon No 1",
            "Balagaon",
            "Ballamguri",
            "Bamni Pahar",
            "Banargaon",
            "Banduguri",
            "Bangsijhora",
            "Bannyaguri pt1",
            "Banyaguri",
            "Barkhangbil",
            "Belatari",
            "Belguri",
            "Bhadulipara",
            "Bhatarmari",
            "Bhatipara",
            "Bhawrijhora",
            "Bhodiaguri",
            "Bhumka",
            "Bishmuri Parta",
            "Borabadha",
            "Boripara No1",
            "Boro Bhatarmari",
            "Boro Gendrabil",
            "Boro Singmari",
            "Boropathar",
            "Chakma",
            "Chautara",
            "Chilingjhora",
            "Dabargaon",
            "Dalgram",
            "Dangarkuti",
            "Diyabari",
            "Dotoma Pt 1",
            "Dotoma Pt 2",
            "Duligaon",
            "Duligaon PT2",
            "Dumbazar",
            "East Sijuguri",
            "Gendrabil",
            "Gohpur",
            "Goybari",
            "Habrubari",
            "Hathimatha",
            "Jadumoni",
            "Jadumoni kokrajhar",
            "Jaleswari",
            "Jambrijhora",
            "Janagaon",
            "Jaraguri No2",
            "Jaymaguri No1",
            "Kathalguri",
            "Katribari",
            "Kumtola",
            "Madhupur",
            "Magurmari",
            "Mainaguri",
            "Mainaobili",
            "Mainaopuri",
            "Mangalahat",
            "Manglajhora",
            "Maojipara",
            "Maurigaon Pt l",
            "Medhipara",
            "Milonpur",
            "Mokrapara",
            "Monglajhora",
            "Morabari",
            "Nabinagar",
            "Naigaon",
            "Namjaipara",
            "Narabari",
            "Nayekgaon",
            "Nepalpara",
            "New Balajan",
            "New Raikhungbari",
            "NO 1 NANDIPUR",
            "NO 1Joyma",
            "No.2 Kanupara",
            "No1 Joyma",
            "No1 Joymar",
            "Pastibari",
            "Patial para",
            "Persuabari",
            "Rainadabri",
            "Ranendrapur FV",
            "Ranighuli",
            "Salakati",
            "Salbari",
            "Samiajhora",
            "Sapkata",
            "Sejari",
            "Serjari",
            "Shijuguri",
            "Shyamdharpara",
            "Shyamthaibari",
            "Shyamthaiwari",
            "Silgara",
            "Siliguri",
            "Simbargaon",
            "South Kajalgaon",
            "Srjari",
            "Sundirijhora",
            "Supariguri",
            "Taraibari",
            "Tasobil",
            "Thagirguri",
            "Thalitbari",
            "Thuribari",
            "Turibari",
            "Ujanpara",
            "W/NO 3"
          ]
        },
        {
          "name": "Lakhimpur",
          "city": [
            "Nalbari Bazar"
          ]
        },
        {
          "name": "Nalbari",
          "city": [
            "1.No.Jaysagar",
            "Bala",
            "Baxirhat",
            "Chatra",
            "Daulashal",
            "Gharuabaha",
            "Jagara",
            "Jalpaiguri",
            "Kakaya",
            "Kakya",
            "Kalag",
            "Kamarkuchi",
            "Khudra Dingdingi",
            "Kotalkuchi",
            "Lachima",
            "Marowa",
            "No. 1. Jaysagar",
            "No.1.kekan kuchi",
            "Pandula",
            "Patuli",
            "Santosh Pur",
            "Ukhura"
          ]
        },
        {
          "name": "Sivasagar",
          "city": [
            "1no konwar gaon",
            "Akhoiphutia",
            "Amakatiya gaon",
            "Bamunmoron gaon",
            "Bhakat gaon",
            "Bhatiapara",
            "Bhutarbari gaon",
            "Bogidol pachali",
            "BOKATA KARANGA GAON",
            "BOKATA NAGAON",
            "Bolo mara miri gaon",
            "BOOKATA KARANGA GAON",
            "Bubhbari",
            "Chakala pathar",
            "CHAKALAPATHAR",
            "Chanimai gaon",
            "Chetia koibartta gaon",
            "Chinatali",
            "Chirakhunda gaon",
            "DHAIBARI",
            "DIMOW",
            "Gahain Gaon",
            "Gelgeli gaon",
            "GODHA BILL",
            "GUDHABIL",
            "Handique gaon",
            "Hemalai moran gaon",
            "Hula gaon",
            "Jamira",
            "Jaradhara",
            "Jaradhara gaon",
            "Joirapar",
            "Kalita gaon",
            "Katanga gaon",
            "Kathapara",
            "Katiari",
            "Konwar dehingia gaon",
            "KONWAR DIHINGIA",
            "KORANGA GAON",
            "kotiori gaon",
            "Ladoigarh missing gaon",
            "Lonpuria gaon",
            "Mahi gaon",
            "Manakata tiniali",
            "Mazenga",
            "Meri chetia gaon",
            "Mithapukhuri",
            "Mogorahat changmai gaon",
            "Mogorahat chetia gaon",
            "Mothachiga",
            "Namdang",
            "NITAI PUKHURI GAON",
            "No.1 konwar gaon",
            "Nowjan",
            "Pata chetia gaon",
            "Pathalial",
            "Raboti gaon",
            "Railung chetia gaon",
            "Rajabari gohain gaon",
            "Reboti gaon",
            "Rupohi Mukh",
            "Samoguri gaon",
            "Sensuwa bongaon",
            "Sensuwa gaon",
            "Singiani",
            "SINGIANI",
            "SIVASAGAR , NAGAOPN GAON",
            "SOONAPUR DEORI",
            "South gelgeli gaon",
            "Sumani gaon",
            "Sundarpukhuri",
            "Tamuli bazar gohain gaon",
            "Taxi mothadang",
            "TENGAPONIA"
          ]
        },
        {
          "name": "Tamulpur",
          "city": [
            "Baraliyapar",
            "Pa",
            "Pas",
            "Paschim naokata"
          ]
        },
        {
          "name": "Tinsukia",
          "city": [
            "Baksa",
            "Coch behar",
            "Dhemaji",
            "Dibrugarh",
            "GUIJAN",
            "Hajo",
            "JANAMUKH",
            "Jorhat",
            "KAKARATOLI GAON",
            "Kakopather",
            "Koch behar",
            "Kochbihar",
            "Margherita",
            "Talap",
            "Tinsukia"
          ]
        },
        {
          "name": "Udalguri",
          "city": [
            "Niz Mugalbecha",
            "Majgaon",
            "Mogalbecha",
            "Dhaldabari",
            "Failaguri , Gossaigaon",
            "Falimari",
            "Bhanukumari",
            "Cooch Bihar",
            "Nalbari",
            "Udalguri ward no 1",
            "Majher Dabri",
            "Jaldhoya",
            "Bagaribari",
            "Boguribari",
            "Chutiyapara",
            "Chutiapara",
            "Simaluguri",
            "Aithanjhar , Simaluguri",
            "Dhupguri",
            "Aithan kokrajhar",
            "Aithanjar",
            "Sagolia",
            "Nakkati gachh , Tufangan",
            "Jaldoha , boxirhat",
            "Balabhut ,Tufanganj",
            "Maheshkuchi",
            "Coochbehar",
            "Kuptimari",
            "Purani Garaibari",
            "Palahgarh , Tangla",
            "Damaruguri",
            "Thepakhat",
            "Deurigaon",
            "Harishinga",
            "Rowta",
            "No 1 Jorpukhuri",
            "No 1 Gormara",
            "Jamuguri , Orang",
            "Gerua bazar , Simaluguri",
            "Gerua Bazar , Dolgaon",
            "Simuluguri",
            "Karaibari , Rowta",
            "No 1 Rowta Station",
            "Mahilapara",
            "Rowta Pathar",
            "Bhalukmari"
          ]
        }
      ]
    },
    {
      "name": "Manipur",
      "districts": [
        "Bishnupur",
        "Imphal East",
        "Imphal West",
        "Senapati",
        "Thoubal"
      ],
      "department": [
        "Department of Advocacy, Consultancy & Projects"
      ],
      "districts_Village": [
        {
          "name": "Bishnupur",
          "city": [
            "Bishnupur",
            "Imphal West",
            "Moirang",
            "Moirang ward no 4",
            "Senapati"
          ]
        },
        {
          "name": "Imphal East",
          "city": [
            "Baksa",
            "Coch behar",
            "Dhemaji",
            "Dibrugarh",
            "GUIJAN",
            "Hajo",
            "JANAMUKH",
            "Jorhat",
            "KAKARATOLI GAON",
            "Kakopather",
            "Koch behar",
            "Kochbihar",
            "Margherita",
            "Talap",
            "Tinsukia"
          ]
        },
        {
          "name": "Imphal West",
          "city": [
            "Heingang",
            "Imphal West",
            "Kontha Ahauup",
            "Kwakeithel Mayaikoibi",
            "Mayang Imphal Municipality Council",
            "Phayeng",
            "Thoubal",
            "Uchiwa",
            "Wangoi"
          ]
        },
        {
          "name": "Senapati",
          "city": [
            "Imphal West",
            "KANEM VILLAGE WILTONG",
            "Khabung",
            "KHONGDEI KHUMAN",
            "Kontha Ahallup",
            "Moirang",
            "Senapati",
            "tadubi",
            "Tamenglony",
            "THINGBA KHUNOU",
            "WILLONG",
            "Willong"
          ]
        }
      ]
    },
    {
      "name": "Mizoram",
      "districts": [
        "Aizawl",
        "Champhai",
        "Lunglei",
        "Serchhip"
      ],
      "department": [
        "Department of Business Development"
      ],
      "districts_Village": [
        {
          "name": "Aizawl",
          "city": [
            "Aisawl",
            "AIZAWL",
            "Champhai",
            "Hnahlan",
            "Hnahthial",
            "Kawlkulh",
            "Ramhlun North",
            "S.Khawbung",
            "Sailam",
            "Thenzawl",
            "Venchhak",
            "Vengthlang",
            "Zuangtui",
            "Aizawl"
          ]
        },
        {
          "name": "Champhai",
          "city": [
            "Aizawl",
            "Champhai",
            "Hnahlan",
            "Kawlkulh",
            "Khawzawl",
            "S.Khawbung",
            "Sailam"
          ]
        },
        {
          "name": "Lunglei",
          "city": [
            "Hnahthial"
          ]
        },
        {
          "name": "Serchhip",
          "city": [
            "Thenzawl",
            "Venchhak",
            "Vengthlang"
          ]
        }
      ]
    },
    {
      "name": "Nagaland",
      "districts": [
        "Dimapur",
        "Phek",
        "Wokha"
      ],
      "department": [
        "Department of Business Development"
      ],
      "districts_Village": [
        {
          "name": "Dimapur",
          "city": [
            "Burma Camp",
            "Dimapur",
            "Dimapur Town",
            "RAGAILONG COLONY BURMA CAMP WARD 4 DIMAPUR"
          ]
        },
        {
          "name": "Phek",
          "city": [
            "Chizami Town",
            "Chizami Village",
            "Enhulumi Village",
            "Pfutsero Town",
            "Pfutseromi Village",
            "Phek Town",
            "Pholami Village",
            "Phusachodu Village",
            "Porba Village",
            "Razeba Town",
            "Thetsumi Village",
            "ZELOME VILAGE",
            "Zhavame",
            "Zhavame Village"
          ]
        },
        {
          "name": "Wokha",
          "city": [
            "Airfield Colony Wokha",
            "Blue Hill Colony Wokha",
            "Changsu Old Wokha",
            "Church Colony Wokha",
            "Elumyo Wokha",
            "Forest Colony Wokha",
            "Longidang Wokha",
            "Longsa Village",
            "Meriyan Village",
            "Molonsu Colony",
            "MTC Colony Wokha",
            "NST Colony Wokha",
            "Okotso Village",
            "PWD Colony Wokha",
            "Tsumang A Wokha",
            "Upper NST Wokha",
            "Vankhosung Wokha",
            "Ward 3 Wokha",
            "Ward 7 Wokha",
            "Woka Sadar",
            "Wokha Sadar",
            "Wokha Village",
            "Yanthamo Wokha",
            "Yikhum Village",
            "Yikhum Village Wokha",
            "Zuvutong Wokha"
          ]
        }
      ]
    },
    {
      "name": "Tripura",
      "districts": [
        "Dhalai",
        "North Tripura",
        "South Tripura",
        "West Tripura"
      ],
      "department": [
        "Department of Advocacy, Consultancy & Projects"
      ],
      "districts_Village": [
        {
          "name": "Dhalai",
          "city": [
            "Bhubanda para",
            "Thali para",
            "Mana Sai para",
            "Kalabari karma para",
            "Haripur para",
            "Jagabandhupara",
            "Dumburnagar",
            "Chawmanu",
            "Halhali",
            "Ambassa",
            "Karnamani para",
            "Royaja para",
            "Raipasa village",
            "Raipassa",
            "Ganganagar",
            "Sarma, Haripur",
            "Bhagya mani para",
            "Durgachhara",
            "Village",
            "Modherchowmoni",
            "Halhali Pathari bosti",
            "Kamalpur",
            "Amtoli",
            "Bilashchara"
          ]
        },
        {
          "name": "North Tripura",
          "city": [
            "Kalapani"
          ]
        },
        {
          "name": "South Tripura",
          "city": [
            "Ashini powang para",
            "Silachari Netaji pally",
            "Birmani para",
            "Chaplin chara para",
            "Rajaram bari para",
            "Nabiram para",
            "Tribeni sadhu para",
            "Sonaichari",
            "Purba kupilong",
            "Kainta bari para ward no 63",
            "Longdar para",
            "31 Laxman para",
            "Manikya para",
            "Noahbari para",
            "Birchandra nagar",
            "Haripur para",
            "Noabari para",
            "Gajendra para",
            "Haluwa para",
            "Sabroom",
            "Udaipur",
            "Atharoblab para",
            "Puwang bari para",
            "Ward no 2",
            "Kusum debbarma para",
            "Bangshi saddar para",
            "Taliya Charan pata",
            "Durganagar",
            "S B school Bindamatilla para",
            "Bhuban Bashi para",
            "Karbook",
            "Muhuripur",
            "Madhu Chandra para",
            "Belonia",
            "Ratanpur",
            "Rupaichari",
            "Brajendra para",
            "Santirbazar",
            "Poangbari",
            "Sundar ban para",
            "Jagyaram para",
            "187 khejur para",
            "Hrishyamukh",
            "Radharam",
            "Ramprasad para",
            "Khargha para",
            "Hrisshyamukh",
            "Prabin Para",
            "Dhanlekha",
            "Chandra para",
            "ADC village Garjanmura",
            "Bagafa",
            "Madhya kathaliachara para",
            "Manu",
            "East Manu kathaliachara para",
            "Bakti ram para",
            "B.C. Nagar, Manu",
            "Gangarai joymangal Para",
            "Joymongal para"
          ]
        },
        {
          "name": "West Tripura",
          "city": [
            "Harirai Chowdhury para",
            "Bisrambari para",
            "Taidu",
            "Malishpur",
            "Krishna mani kobra para",
            "Patni",
            "Belbari sova mani para",
            "Ranirbazar",
            "Majlishpur",
            "Jirania",
            "Mandwi",
            "Bagaban kobra para",
            "Bisra",
            "Bishram Bari para",
            "Kunja bihari para",
            "Chamalia",
            "A .D.C Village",
            "Khowa",
            "Khowai",
            "North durganagar",
            "North durganagar para",
            "Debichhara para",
            "Kumari bill para",
            "Durganagar para",
            "Kumaritila para",
            "Fatikchara",
            "Kamalghat",
            "Nandanagar Agartala"
          ]
        }
      ]
    }
  ]
}
    ''';
